apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nyancat-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jakoubektom/kcd-2024.git'
    targetRevision: HEAD
    path: '.'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kcd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true